all : flash

TARGET:=a_useless_button
ADDITIONAL_C_FILES+=1_Foundation/fun_button.h 3_Nrf/nrf24l01_low_level.c 3_Nrf/nrf24l01.c

include ../../ch32v003fun/ch32v003fun.mk

flash : cv_flash
clean : cv_clean


