all : flash

TARGET:=a_useless_button
ADDITIONAL_C_FILES+=1Foundation/fun_button.h 2Nrf/nrf24l01_low_level.c 2Nrf/nrf24l01.c 2Nrf/nrf24l01_main.h

include ../../ch32v003fun/ch32v003fun.mk

flash : cv_flash
clean : cv_clean


